FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:14

# Install MySQL client
RUN apt-get update && apt-get install -y mysql-client && apt-get clean

# Install Expo CLI for React Native
RUN npm install -g expo-cli

# Install Sequelize CLI for Backend
RUN npm install -g sequelize-cli